Repository Splendor-Mobile-Game/ClientSide, pull requests merged in 2023-05, with the labels that each got.

#105 Implement `GameEndingController`
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/GameEndingController.java
  app/src/main/java/com/example/splendormobilegame/model/Game.java
Labels: type: feature

#109 Implement Player Verification in `endTurn` Method of `TurnController`
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/TurnController.java
Labels: type: fix

#122 Reaction unit tests
  app/build.gradle
  app/src/main/java/com/example/splendormobilegame/Controller.java
  app/src/main/java/com/example/splendormobilegame/MainActivity.java
  app/src/main/java/com/example/splendormobilegame/activities/CreateRoom/CreateRoomActivity.java
  app/src/main/java/com/example/splendormobilegame/activities/CreateRoom/CreateRoomController.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/BuyingReservedCardsController.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/BuyingRevealedCardsController.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/DeckReservingController.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/EndTurnController.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/GameActivity.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/GameEndingController.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/LeavingController.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/NobleController.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/RevealedCardsReservingController.java
  app/src/main/java/com/example/splendormobilegame/activities/GameActivity/TokensController.java
  app/src/main/java/com/example/splendormobilegame/activities/JoinRoom/JoinRoomActivity.java
  app/src/main/java/com/example/splendormobilegame/activities/JoinRoom/JoinRoomController.java
  app/src/main/java/com/example/splendormobilegame/activities/WaitingRoom/JoiningController.java
  app/src/main/java/com/example/splendormobilegame/activities/WaitingRoom/LeavingController.java
  app/src/main/java/com/example/splendormobilegame/activities/WaitingRoom/NewRoomOwnerController.java
  app/src/main/java/com/example/splendormobilegame/activities/WaitingRoom/StartGameController.java
  app/src/main/java/com/example/splendormobilegame/activities/WaitingRoom/WaitingRoomActivity.java
  app/src/main/java/com/example/splendormobilegame/model/Model.java
  app/src/main/java/com/example/splendormobilegame/websocket/CustomWebSocketClient.java
  app/src/test/java/com/example/splendormobilegame/activities/GameActivity/DeckReservingControllerTests.java
Labels: type: testing

#164 Return if no reaction assigned to message
  app/src/main/java/com/example/splendormobilegame/websocket/CustomWebSocketClient.java
Labels: type: fix

#178 Fix serialize json nulls
  app/build.gradle
  app/src/main/java/com/example/splendormobilegame/websocket/ReactionUtils.java
Labels: type: fix
