Repository Splendor-Mobile-Game/ClientSide, pull requests merged in 2023-03, with the labels that each got.

#11 Added .idea folder to .gitignore
  .gitignore
Labels: refactor

#15 Add server repo as dependency
  app/build.gradle
  settings.gradle
Labels: enhancement

#16 Make websocket client more programmer friendly
  app/proguard-rules.pro
  app/src/main/java/com/example/splendormobilegame/CreateRoomActivity.java
  app/src/main/java/com/example/splendormobilegame/MainActivity.java
  app/src/main/java/com/example/splendormobilegame/WebSocket.java
  app/src/main/java/com/example/splendormobilegame/websocket/CustomWebSocketClient.java
  app/src/main/java/com/example/splendormobilegame/websocket/Model.java
  app/src/main/java/com/example/splendormobilegame/websocket/NotInitializedException.java
  app/src/main/java/com/example/splendormobilegame/websocket/UserReaction.java
  app/src/main/java/com/example/splendormobilegame/websocket/reactions/CreateRoomResponse.java
Labels: type: feature
